# package: goserver
language: go
sudo: required
dist: trusty
go:
- '1.11'
# deploy:
#   provider: heroku
#   app: go-todo-rest-api-example
#   on:
#     repo: Dandavthink/go-todo-rest-api-example
#   api_key:
#     secure: nzYsM9lxjKftPwDLN/QdIChI3kCpbs3mV1/DA6+bl1ZgY/Fhol0NdmaaJgayQy82/vkoVNSpSx2cOWM4AJGBWGlussg35Tdr0dovv63Ept9tVzbGnB9EwUhsO8Tlz3dStzrnxnQWSmNoWHU5o/ub9HssxglT0KXZiE6HCLNQuQ0TqSzy7+IPJegzLhd+z9BuGm2F3ASEwrToxnoNGRIixSRXZ+TDRKUTaP3mRUmkRdN2YXfuB6JT1w7dpFptndJYXdoYXlll468A3kbUoAgyHXXtoKVFP4vR0gfHA8QxbBbbGP6Yb+5FI8yhQ3lZ5nd1ac6GC2nfDjPEJRg38kSRHXCHHyaosp8Nw30z+UBCoD8hr4YJVifiwYr6IntWvOo9EhgSQlUojuzRSRstJa5KuN+nOSEp0tmUr3XXaF2nlJlC3I0zsxLwuGQjs3w0ODC3NgMiz6kcXYJY8zn4Joop0CShTqEPIaeHwF6XsMOhXwLRBZwPAav3I+m7HTW24oUgRik8GyClEjatWZWSrI4LmNEtnQMVn5MQACJDjIMhQlke/vb3ZcYl7oKosKmrlbZWKFE6gh+aYxLEnnlD/baI1j4KsMO5bnDtBE2lYBjXjkmHwjkp4xSk9+J3S11gba5grwOFwwSnJbqe2be500I7mCNI+MvWQbpZkwV/jmmsITQ=

install:
- npm install -g newman

before_script:
- node --version
- npm --version
- newman --version
- chmod +x ./tests/test_run.sh
# - gem install travis$ travis encrypt $(heroku auth:token) --add deploy.api_key
# - gem install dpl
# - dpl --provider=heroku --app=quailapp --api-key=$HEROKU_PRODUCTION_API_KEY
# only:
  #  - master
# after_deploy:
# - "./tests/test_run.sh"
script:
# - "./tests/test_run.sh"

deploy:
  provider: heroku
  app: go-todo-rest-api-example
  on:
    repo: Dandavthink/go-todo-rest-api-example
    branch: master
  api_key:
    secure: hwO1NwlYdYFbfrn0QDM9OZhU3Op7ef6+Ab8MMHcexftBH/KA4LTuJy6Z/XKi6wVz+4rDqgWlwtrXUdPIVMGNmMne0hFmKdvNZj9yKhRy4P/X67HzxlfxRXmAYni8QFIQ8V0KIBqpnXgBvMb2WiJGX3NlBwOGV3uoi2ObokZrO9jESpf3viEoBzGmLbgerycJ254W9UaRfhk1r4u18qyGWgKEFOrjQYn5/nVCovA8ZKD+kYrvH8V+S7LQdTn05Lkvy9AiGx+6Qj9Dq+AlIFqQkJ1yC52eT8yqZdHnV7GPNwAbTIBGMc9P0q8PRdUAYPyUcgZLP71Cv9PssBSrFXWBibmsbTEsDroq1UaGRzKumnauY9+TgMEzhtmnUHk1qe00zPVJK9zqTDU2FEMhn2jnCtdesTG3eFE/zHP1rTgU3w/ErMRxW2/cP4DDAyHUGnKd1hQRz8N2MPwFlh7qR5oEl38JPxNog0V0sDMn+obIBlR0oSDN6j0WrkpGNexAdtY8Qgx+hiaI6Jzg349YD3+CAR0cah+PLIvhyL7PHVr5CCBHZKXde7s8p5EqIHPX0VgHPVd4UuVE2V4X5rauD0zpb/aW/5XlkzTXh7TVQSu0iKboCVexeQOqALwBgD71yCRIY0VMhhz8qyxYxiLXVH9GHjjLGg88qo5EWzGMhvVbU94=
  
after_deploy:
- "./tests/test_run.sh"
