language: go
sudo: required
dist: trusty
go:
- '1.11'
env:
  global:
  - BASE_HOST=127.0.0.1
  - LOG_LEVEL=0
 branches:
  only:
  - master
install:
- npm install -g newman
  on:
    branch: master



