language: go
sudo: required
dist: trusty
go:
- '1.11'
#env:
#  global:
#  - BASE_HOST=https://travis-ci-demo1.herokuapp.com/
#   # - LOG_LEVEL=0
# branches:
#   only:
#   - master
deploy:
  provider: heroku
  # api_key:
  #   secure: <your-api-key>
  app: go-todo-rest-api-example
  on:
    repo: Dandavthink/go-todo-rest-api-example
install:
- npm install -g newman
before_script:
  - node --version
  - npm --version
  # - node_modules/.bin/newman --version
  - newman --version
  - chmod +x ./tests/test_run.sh
script:
 - "./tests/test_run.sh"
#   on:
#     branch: master



