language: go
sudo: required
dist: trusty
go:
- '1.11'
#env:
#  global:
#  - BASE_HOST=127.0.0.1
#   # - LOG_LEVEL=0
# branches:
#   only:
#   - master
install:
- npm install -g newman
before_script:
  - node --version
  - npm --version
  # - node_modules/.bin/newman --version
  - newman --version
  - chmod +x ./tests/test_run.sh
script:
 - "./tests/test_run.sh"
#   on:
#     branch: master



